# Imports

In [2]:
import numpy as np
import torch
arr1 = np.array([0, 1, 2, 3])
arr2 = np.array([0, 1, 3, 4])

((arr1 == arr2) & (arr1 < arr2)).any()


np.False_

In [3]:
mask = np.array([[True, False, False,],
                [True, True, False]])
print(f"{mask.shape = }")

print(f"{mask.all() = }")
print(f"{mask.any() = }")

mask.shape = (2, 3)
mask.all() = np.False_
mask.any() = np.True_


In [4]:
print(f"{mask.all(0) = }")
print(f"{mask.all(0).all(0) = }")
print(f"{mask.all(0).any(0) = }")

print(f"{mask.any(0) = }")
print(f"{mask.any(0).all(0) = }")
print(f"{mask.any(0).any(0) = }")

mask.all(0) = array([ True, False, False])
mask.all(0).all(0) = np.False_
mask.all(0).any(0) = np.True_
mask.any(0) = array([ True,  True, False])
mask.any(0).all(0) = np.False_
mask.any(0).any(0) = np.True_


## Find Given Value From an Array

In [5]:
arr = np.array([[1, 2, 3],[1, 1, 1]])
print(arr)
print(arr == 1)
print(np.where(arr == 1))
wh = np.where(arr == 1)
for i in range(len(wh[0])):
    assert arr[wh[0][i], wh[1][i]] == 1

[[1 2 3]
 [1 1 1]]
[[ True False False]
 [ True  True  True]]
(array([0, 1, 1, 1]), array([0, 0, 1, 2]))


In [6]:
arr = np.array([1, 2, 3])
print(arr)
print(arr == 1)
print(np.where(arr == 1))
wh = np.where(arr == 1)
for i in range(len(wh[0])):
    assert arr[wh[0][i]] == 1

[1 2 3]
[ True False False]
(array([0]),)


In [7]:
tup = (1, 2)
a = (1,2)
b, c = 1, 2
print(a)
print(f"{b = }, {c = }")

tup = (2,)
a = tup
b, = tup
print(f"{a = }")
print(f"{b = }")

(1, 2)
b = 1, c = 2
a = (2,)
b = 2


# PyTorch Practice

## Tensor Practice

### a. torch.zeros

In [8]:
a = torch.zeros(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### b. torch.zeros_like

In [9]:
b=torch.zeros_like(a) # copies shape of input tensor and makes all value to 0
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### c.torch.tensor

In [10]:
data = [[1,2], [3,4]]
c=torch.tensor(data)
print(c)

tensor([[1, 2],
        [3, 4]])


### d. torch.zeros_like 2

In [11]:
d=torch.zeros_like(c) # copies shape of input tensor and makes all value to 0
print(d)

tensor([[0, 0],
        [0, 0]])


### e. torch 3 Dimensions

In [12]:
e=torch.zeros((2,2,2)).float() # Two 2x2 Matrix
print(e)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


### f. Slicing Tensor

In [13]:
f=torch.zeros((5,3,16)).float()
f[ :, :3, 0 ] = 3 
f[ :, 3:, 1:] = 0.0 
print(f)
print(f.shape[0])

tensor([[[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0.,

In [14]:
n=1
m=2
print(f[:,:,0:1])
print(f[:,:,0:1].transpose(n, m)) # Transposes nth dimension and mth dimension

tensor([[[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]]])
tensor([[[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]]])


### g. Slicing and assigning values 

In [15]:
g=torch.zeros((f.shape[0], 4), device="cuda")

print(g)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


In [16]:
g[:, 0]=1
print(g)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]], device='cuda:0')


## torch.rand_like

In [ ]:
noise = torch.rand_like(g) # g와 똑같은 크기를 가진 tensor에 랜덤 값을 넣어서 tensor를 생성한다.
print(noise)

tensor([[0.9984, 0.5758, 0.4909, 0.1165],
        [0.5282, 0.1829, 0.3414, 0.0253],
        [0.4720, 0.3605, 0.1729, 0.2439],
        [0.0223, 0.1973, 0.4070, 0.5619],
        [0.0660, 0.5201, 0.2197, 0.7605]], device='cuda:0')


### h. Making Identity Matrix

In [ ]:
n=3
m=4
h=torch.eye(n,m) # nxm Identity matrix
print(h)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


## I. Slicing 2

In [25]:
s=torch.tensor([[1,1,1],[2,3,3]])
L = torch.zeros((s.shape[0], 3, 3), dtype=torch.float, device="cuda")
L[:,0,0] = s[:,0]
L[:,1,1] = s[:,1]
L[:,2,2] = s[:,2]
print(L)

tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[2., 0., 0.],
         [0., 3., 0.],
         [0., 0., 3.]]], device='cuda:0')


## NN Practice

## list code details

In [1]:
v = list(range(10))
print(v)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
