# Imports

In [1]:
import numpy as np
import torch
arr1 = np.array([0, 1, 2, 3])
arr2 = np.array([0, 1, 3, 4])

((arr1 == arr2) & (arr1 < arr2)).any()


False

In [2]:
mask = np.array([[True, False, False,],
                [True, True, False]])
print(f"{mask.shape = }")

print(f"{mask.all() = }")
print(f"{mask.any() = }")

mask.shape = (2, 3)
mask.all() = False
mask.any() = True


In [3]:
print(f"{mask.all(0) = }")
print(f"{mask.all(0).all(0) = }")
print(f"{mask.all(0).any(0) = }")

print(f"{mask.any(0) = }")
print(f"{mask.any(0).all(0) = }")
print(f"{mask.any(0).any(0) = }")

mask.all(0) = array([ True, False, False])
mask.all(0).all(0) = False
mask.all(0).any(0) = True
mask.any(0) = array([ True,  True, False])
mask.any(0).all(0) = False
mask.any(0).any(0) = True


## Find Given Value From an Array

In [4]:
arr = np.array([[1, 2, 3],[1, 1, 1]])
print(arr)
print(arr == 1)
print(np.where(arr == 1))
wh = np.where(arr == 1)
for i in range(len(wh[0])):
    assert arr[wh[0][i], wh[1][i]] == 1

[[1 2 3]
 [1 1 1]]
[[ True False False]
 [ True  True  True]]
(array([0, 1, 1, 1], dtype=int64), array([0, 0, 1, 2], dtype=int64))


In [5]:
arr = np.array([1, 2, 3])
print(arr)
print(arr == 1)
print(np.where(arr == 1))
wh = np.where(arr == 1)
for i in range(len(wh[0])):
    assert arr[wh[0][i]] == 1

[1 2 3]
[ True False False]
(array([0], dtype=int64),)


In [6]:
tup = (1, 2)
a = (1,2)
b, c = 1, 2
print(a)
print(f"{b = }, {c = }")

tup = (2,)
a = tup
b, = tup
print(f"{a = }")
print(f"{b = }")

(1, 2)
b = 1, c = 2
a = (2,)
b = 2


# PyTorch Practice

## Tensor Practice

### a. torch.zeros

In [7]:
a = torch.zeros(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### b. torch.zeros_like

In [8]:
b=torch.zeros_like(a) # copies shape of input tensor and makes all value to 0
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### c.torch.tensor

In [9]:
data = [[1,2], [3,4]]
c=torch.tensor(data)
print(c)

tensor([[1, 2],
        [3, 4]])


### d. torch.zeros_like 2

In [10]:
d=torch.zeros_like(c) # copies shape of input tensor and makes all value to 0
print(d)

tensor([[0, 0],
        [0, 0]])


### e. torch 3 Dimensions

In [11]:
e=torch.zeros((3,2,2)).float() # Two 2x2 Matrix
print(e)
print(e[0])

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[0., 0.],
        [0., 0.]])


### f. Slicing Tensor

In [12]:
f=torch.zeros((5,3,16)).float()
f[ :, :3, 0 ] = 3 
f[ :, 3:, 1:] = 0.0 
print(f)
print(f.shape[0])

tensor([[[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [3., 0.,

In [13]:
n=1
m=2
print(f[:,:,0:1])
print(f[:,:,0:1].transpose(n, m)) # Transposes nth dimension and mth dimension

tensor([[[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [3.]]])
tensor([[[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]]])


### g. Slicing and assigning values 

In [14]:
g=torch.zeros((f.shape[0], 4), device="cuda")

print(g)

c:\Users\COM\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\cuda\__init__.py:218: UserWarning: 
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


In [15]:
g[:, 0]=1
print(g)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]], device='cuda:0')


## torch.rand_like

In [16]:
noise = torch.rand_like(g) # g와 똑같은 크기를 가진 tensor에 랜덤 값을 넣어서 tensor를 생성한다.
print(noise)

tensor([[0.3991, 0.0155, 0.7671, 0.1448],
        [0.0767, 0.5810, 0.4206, 0.4403],
        [0.2347, 0.7358, 0.2725, 0.8002],
        [0.8243, 0.9712, 0.6435, 0.0541],
        [0.0803, 0.4609, 0.3446, 0.6460]], device='cuda:0')


### h. Making Identity Matrix

In [17]:
n=3
m=4
h=torch.eye(n,m) # nxm Identity matrix
print(h)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


## I. Slicing 2

In [18]:
s=torch.tensor([[1,1,1],[2,3,3]])
L = torch.zeros((s.shape[0], 3, 3), dtype=torch.float, device="cuda")
L[:,0,0] = s[:,0]
L[:,1,1] = s[:,1]
L[:,2,2] = s[:,2]
print(L)

tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[2., 0., 0.],
         [0., 3., 0.],
         [0., 0., 3.]]], device='cuda:0')


## J. making new torch

In [19]:
# gaussians.max_radii2D[visibility_filter]
print(type(a), type(b))

<class 'torch.Tensor'> <class 'torch.Tensor'>


# NN Practice

In [20]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

# list code details

In [21]:
v = list(range(10))
print(v)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
