In [5]:
import numpy as np
arr1 = np.array([0, 1, 2, 3])
arr2 = np.array([0, 1, 3, 4])

((arr1 == arr2) & (arr1 < arr2)).any()


np.False_

In [7]:
mask = np.array([[True, False, False,],
                [True, True, False]])
print(f"{mask.shape = }")

print(f"{mask.all() = }")
print(f"{mask.any() = }")

mask.shape = (2, 3)
mask.all() = np.False_
mask.any() = np.True_


In [10]:
print(f"{mask.all(0) = }")
print(f"{mask.all(0).all(0) = }")
print(f"{mask.all(0).any(0) = }")

print(f"{mask.any(0) = }")
print(f"{mask.any(0).all(0) = }")
print(f"{mask.any(0).any(0) = }")

mask.all(0) = array([ True, False, False])
mask.all(0).all(0) = np.False_
mask.all(0).any(0) = np.True_
mask.any(0) = array([ True,  True, False])
mask.any(0).all(0) = np.False_
mask.any(0).any(0) = np.True_


## Find Given Value From an Array

In [13]:
arr = np.array([[1, 2, 3],[1, 1, 1]])
print(arr)
print(arr == 1)
print(np.where(arr == 1))
wh = np.where(arr == 1)
for i in range(len(wh[0])):
    assert arr[wh[0][i], wh[1][i]] == 1

[[1 2 3]
 [1 1 1]]
[[ True False False]
 [ True  True  True]]
(array([0, 1, 1, 1]), array([0, 0, 1, 2]))


In [15]:
arr = np.array([1, 2, 3])
print(arr)
print(arr == 1)
print(np.where(arr == 1))
wh = np.where(arr == 1)
for i in range(len(wh[0])):
    assert arr[wh[0][i]] == 1

[1 2 3]
[ True False False]
(array([0]),)


In [16]:
tup = (1, 2)
a = (1,2)
b, c = 1, 2
print(a)
print(f"{b = }, {c = }")

tup = (2,)
a = tup
b, = tup
print(f"{a = }")
print(f"{b = }")

(1, 2)
b = 1, c = 2
a = (2,)
b = 2
