# Imports

* 무거운 "train" 작업 전체의 input의 output만 보고하는 튜토리얼 작성하고
* 그러고 나면 다음 단계로, train과정에서 들어가는 함수들을 쪼개서 분석해보는 tutorial도 해보기
  * `train.py`에서 호출하는 세부 모듈을 그대로 가져다 쓰되, train.py의 전체 흐름을 조금 더 가볍게 뫄하는 별도 스크립트 작성이 필요할 것으로 보임.


  train.py의 input이 뭔지 파악이 되고 나면 전체 프로그램의 흐름(모듈 간 의존관계)를 다이어그램(ppt)으로 그려보기
  * 핵심은, "특정 기능만 사용/분석 하려고 하면 뭐는 몰라도 되느냐"

  생각날 때 틈틈이:
     * 3DGS 발전 방향 고민 및 최근 연구 탐색(검색)해보기
     * multi-view 이미지를 3DGS 형태로 복원 --> mesh 형태로 변환하는

In [2]:
import os
import torch
import numpy as np
import open3d as o3d
from random import randint
from utils.loss_utils import l1_loss, ssim
from gaussian_renderer import render, network_gui
import sys
from scene import Scene, GaussianModel
from utils.general_utils import safe_state, get_expon_lr_func
import uuid
from tqdm import tqdm
from utils.image_utils import psnr
from argparse import ArgumentParser, Namespace
from arguments import ModelParams, PipelineParams, OptimizationParams
from scene.dataset_readers import sceneLoadTypeCallbacks
try:
    from torch.utils.tensorboard import SummaryWriter
    TENSORBOARD_FOUND = True
except ImportError:
    TENSORBOARD_FOUND = False

try:
    from fused_ssim import fused_ssim
    FUSED_SSIM_AVAILABLE = True
except:
    FUSED_SSIM_AVAILABLE = False

try:
    from diff_gaussian_rasterization import SparseGaussianAdam
    SPARSE_ADAM_AVAILABLE = True
except:
    SPARSE_ADAM_AVAILABLE = False

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


# Running train.py

We will run the following terminal command:

```cmd
python train.py -s Gaussiatest/Test2
```

Here this command assumes there are already points3D.ply which is the output of convet.py in [GaussianTest/Test2/sparse/0](GaussianTest/Test2/sparse/0)

# Input

`train.py`에 정의되어 있는 `training`이라는 함수에  

```python
# `train.py`
def training(...):
    ...
    gaussians = GaussianModel(dataset.sh_degree, opt.optimizer_type)  
    scene = Scene(dataset, gaussians) # Here
```

```python
# `scene/__init__.py`
class Scene:
    ...
    def __init__(self, args : ModelParams, gaussians : GaussianModel, load_iteration=None, shuffle=True, resolution_scales=[1.0]):
        ...
        if os.path.exists(os.path.join(args.source_path, "sparse")):
            scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.depths, args.eval, args.train_test_exp) # Here
```

```python
# `scene/dataset_readers`
sceneLoadTypeCallbacks = { # Line 312
    "Colmap": readColmapSceneInfo, # Here
    "Blender" : readNerfSyntheticInfo
}

def readColmapSceneInfo(path, images, depths, eval, train_test_exp, llffhold=8): # Line 145
    try:
        cameras_extrinsic_file = os.path.join(path, "sparse/0", "images.bin")
        cameras_intrinsic_file = os.path.join(path, "sparse/0", "cameras.bin")
        cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
        cam_intrinsics = read_intrinsics_binary(cameras_intrinsic_file)
    except:
        cameras_extrinsic_file = os.path.join(path, "sparse/0", "images.txt")
        cameras_intrinsic_file = os.path.join(path, "sparse/0", "cameras.txt")
        cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
        cam_intrinsics = read_intrinsics_text(cameras_intrinsic_file)

    depth_params_file = os.path.join(path, "sparse/0", "depth_params.json")
    ...

    cam_infos_unsorted = readColmapCameras(...) # returns CameraInfo objects
    cam_infos = sorted(cam_infos_unsorted.copy(), key = lambda x : x.image_name)

    train_cam_infos = [c for c in cam_infos if train_test_exp or not c.is_test] # scene_info's train_cameras
    test_cam_infos = [c for c in cam_infos if c.is_test] # scene_info's test_cameras
    ...
    ply_path = os.path.join(path, "sparse/0/points3D.ply") # scene_info's ply_path
    ...
    pcd = fetchPly(ply_path) # scene_info's point_cloud
    ...

    scene_info = SceneInfo(point_cloud=pcd,
                           train_cameras=train_cam_infos,
                           test_cameras=test_cam_infos,
                           nerf_normalization=nerf_normalization,
                           ply_path=ply_path,
                           is_nerf_synthetic=False)
    return scene_info
```



pcd를 불러오기 위한 `fetchply` 함수
```python
    def fetchPly(path):
        plydata = PlyData.read(path)
        vertices = plydata['vertex']
        positions = np.vstack([vertices['x'], vertices['y'], vertices['z']]).T
        colors = np.vstack([vertices['red'], vertices['green'], vertices['blue']]).T / 255.0
        normals = np.vstack([vertices['nx'], vertices['ny'], vertices['nz']]).T
        return BasicPointCloud(points=positions, colors=colors, normals=normals)
```



input.ply가 생성되는 부분
```python
# scene.__init__.py
# Line 51
if not self.loaded_iter:
    with open(scene_info.ply_path, 'rb') as src_file, open(os.path.join(self.model_path, "input.ply") , 'wb') as dest_file:
        dest_file.write(src_file.read())

```

위와 같은 코드가 있는데 `Scene` 클래스에서 `scene.dataset_readers`의 `sceneLoadTypeCallbacks["Colmap"]`라는 메소드로 [tutorial_convert_py.ipynb](tutorial_convert_py.ipynb)에서 했던 것과 같이 `Image Undistorter`가 진행된 후의 images.bin 파일과 cameras.bin 파일을 읽어온다. 이 값들을 `scene_info` 변수가 가져오고 `prepare_output_and_logger` 메소드가 설정한 [args.model_path](output/Test2_Result)에 `input.ply`(새로 만들어짐) 파일로 [GaussianTest/Test2/sparse/0](GaussianTest/Test2/sparse/0)/point3D.ply의 값을 복사하여 가져온다. 이를 GaussianModel 클래스의 `create_from_pcd` 메소드를 이용해 3D Gaussian을 만든다.

## Input.ply

In [ ]:
ply_path = 'output/Test2_Result/input.ply'
pcd = o3d.io.read_point_cloud(ply_path)

print(pcd)
points = np.asarray(pcd.points)
print(points)

o3d.visualization.draw_geometries([pcd])

PointCloud with 21021 points.
[[ 4.8563242   1.49756932  9.32258797]
 [ 4.42609215  0.2964223   8.79938507]
 [-0.22115773  1.75190425  2.11942744]
 ...
 [-0.84992254  1.30992627  1.76135576]
 [-0.25466967  4.85330391  4.3301754 ]
 [-0.11436929  4.94564438  4.25144577]]


# create_from_pcd

`Scene` 클래스 객체를 생성하는데 있어 마지막으로 실행하는 함수이다. 이 함수가 무엇을 하는지 알아보고자 한다. 

```python
# scene.__init__.py
self.gaussians.create_from_pcd(scene_info.point_cloud, scene_info.train_cameras, self.cameras_extent) # Line 83


# scene.gaussian_model.py
def create_from_pcd(self, pcd : BasicPointCloud, cam_infos : int, spatial_lr_scale : float):
```

## Parameters

`pcd:` input에서 봤던 SceneInfo 객체의 point_cloud 값을 가져온다. 이는 BasicPointCloud 클래스의 객체이고 input.ply의 내용이 담겨져 있다.  
```python
BasicPointCloud(points=positions, colors=colors, normals=normals)

```

`cam_infos:` SceneInfo 객체의 train_cameras의 값을 가져온다. train_cameras는 `readColmapCameras`의 return 값인 `CameraInfo` 객체를 가지고 있다. 이 파라미터는 코드 내에서 실제로는 len(cam_infos)로만 사용되기에 `int`로 처리되었다.
```python
# scene.dataset_readers.py Line 194
cam_infos_unsorted = readColmapCameras(...) # returns CameraInfo objects
cam_infos = sorted(cam_infos_unsorted.copy(), key = lambda x : x.image_name) 

train_cam_infos = [c for c in cam_infos if train_test_exp or not c.is_test] # scene_info's train_cameras

```
`spatial_lr_scale:` SceneInfo 객체의 `nerf_normalization[radius]` 값을 가져오는데 이는 `getNerfppNorm`이라는 함수가 SceneInfo 객체의 `train_cam_infos`에 속한 다수의 카메라 좌표들을 구해 중심을 구하고 그 중심에서 가장 먼 카메라와의 거리를 이용해 정규화를 시켜 씬의 전체 크기를 가늠하는 기준 scale 값으로 사용한다.
```python
# scene.dataset_readers.py Line 203
nerf_normalization = getNerfppNorm(train_cam_infos)

def getNerfppNorm(cam_info):
    ...
    return {"translate": translate, "radius": radius}
```

## How it works

```python
self.spatial_lr_scale = spatial_lr_scale

```
`GaussianModel` 클래스의 멤버 변수인 `spatial_lr_scale`에 파라미터로 받아온 `self.camera_extent` 값을 할당한다.
```python


"""Recall
class BasicPointCloud(NamedTuple):
    points : np.array
    colors : np.array
    normals : np.array
"""

fused_point_cloud = torch.tensor(np.asarray(pcd.points)).float().cuda()
fused_color = RGB2SH(torch.tensor(np.asarray(pcd.colors)).float().cuda())
```
`fused_point_cloud` 변수에 `pcd`의 `points`에 해당하는 값들을 float형 array로 받아오고 이를 GPU에서 계산할 수 있도록 한다.  
`fused_color` 변수에 `pcd`의 `corlors`에 해당하는 값들을 SH의 초기 계수로 변환하여 float형 array로 받아오고 이를 GPU에서 계산할 수 있도록 한다.

**학습을 더 용이하게 하기 위하여 RGB 값을 SH의 초기 계수로 변환하는 과정을 거친다.**
```python

features = torch.zeros((fused_color.shape[0], 3, (self.max_sh_degree + 1) ** 2)).float().cuda()
features[:, :3, 0 ] = fused_color
features[:, 3:, 1:] = 0.0
```
`features` 변수에 0으로 차 있는 `fused_color.shape[0]`개의 `3x16 행렬` ($\because$ max_sh_degree $== 3$) 을 만든다.  
각 `3x16 행렬`의 처음 3행의 첫 번째 열의 값을 RGB 값으로 채우고 나머지는 전부 0으로 한다. 
```python

dist2 = torch.clamp_min(distCUDA2(torch.from_numpy(np.asarray(pcd.points)).float().cuda()), 0.0000001)
scales = torch.log(torch.sqrt(dist2))[...,None].repeat(1, 3)
rots = torch.zeros((fused_point_cloud.shape[0], 4), device="cuda")
rots[:, 0] = 1

opacities = self.inverse_opacity_activation(0.1 * torch.ones((fused_point_cloud.shape[0], 1), dtype=torch.float, device="cuda")) # Here

# scene.gaussian_model.py Line 45
self.inverse_opacity_activation = inverse_sigmoid

# utils.general_utils.py Line 18
def inverse_sigmoid(x):
    return torch.log(x/(1-x))
```
`dist2:` 가장 가까운 점과의 거리의 제곱을 0.0000001보다 크게 하여 dist2에 tensor로 저장.  
`scales:` 루트를 씌워 거리를 구한다.  
`rots:` point cloud의 전체 개수에 대해 `quaternion`의 `w` 값을 1로 함으로써 각 점에 대해 아무런 회전도 하지 않은 상태로 만든다.  
`opacities:` 1로 채워진 nx1 행렬을 만들어 `inverse_sigmoid`에 넣는다.
```python

self._xyz = nn.Parameter(fused_point_cloud.requires_grad_(True)) # Line 166
...
exposure = torch.eye(3, 4, device="cuda")[None].repeat(len(cam_infos), 1, 1)
self._exposure = nn.Parameter(exposure.requires_grad_(True)) # Line 176
```
`GaussianModel` 클래스의 각 멤버 변수들을 `nn.Parameter(...)`를 통해 학습이 가능한 값들로 만든다.

# Training Setup

```python
gaussians.training_setup(opt)
```
Let's look at `training_setup` method  
This is `GaussianModel` class's method

## Parameters

```python
def training_setup(self, training_args):
```
`training_args`: Object of `OptimizationParams` class

## How it works

```python
self.percent_dense = training_args.percent_dense
self.xyz_gradient_accum = torch.zeros((self.get_xyz.shape[0], 1), device="cuda")
self.denom = torch.zeros((self.get_xyz.shape[0], 1), device="cuda")
```
`opt.percent_dense:` is hardcoded as 0.01 so `gaussians.percent_dense` gets `0.01` as its value.  
`gaussians.xyz_gradient_accum:` gets tensor with (the number of points)x1 size as its value (_for Test2, 1768 points are input points so it gets 1768x1 tensor_)  
`gaussians.denom:` gets the same value as gaussians.xyz_gradient_accum

```python
l = [
    {'params': [self._xyz], 'lr': training_args.position_lr_init * self.spatial_lr_scale, "name": "xyz"},
    {'params': [self._features_dc], 'lr': training_args.feature_lr, "name": "f_dc"},
    {'params': [self._features_rest], 'lr': training_args.feature_lr / 20.0, "name": "f_rest"},
    {'params': [self._opacity], 'lr': training_args.opacity_lr, "name": "opacity"},
    {'params': [self._scaling], 'lr': training_args.scaling_lr, "name": "scaling"},
    {'params': [self._rotation], 'lr': training_args.rotation_lr, "name": "rotation"}
]
```
To set each parameter's learning rate(lr) differently, code makes a list of dictionary  

```python
if self.optimizer_type == "default":
    self.optimizer = torch.optim.Adam(l, lr=0.0, eps=1e-15)
```
Since `gaussians.optimizer_type` is *"default"* in our tutorial, `gaussians.optimizer` is set to *torch.optim.Adam(l, lr = 0.0, eps = 1e-15)*

```python
self.exposure_optimizer = torch.optim.Adam([self._exposure])
```
`self._exposure` is set by *create_from_pcd*  
```python
# inside create_from_pcd, gaussian_model.py Line 175
exposure = torch.eye(3, 4, device="cuda")[None].repeat(len(cam_infos), 1, 1)
self._exposure = nn.Parameter(exposure.requires_grad_(True))
```
which contains number of cameras' $3*4$ identical matrices *(For details look at [tutorial_3DGS](tutorial_3DGS.ipynb) Chapter `training function initialize/create_from_pcd details`)*

## get_expon_lr_func
Inside the `training_setup` method, `get_expon_lr_func` method is called. So, we are going to look at how it works

```python
# Inside training_setup
self.xyz_scheduler_args = get_expon_lr_func(lr_init=training_args.position_lr_init*self.spatial_lr_scale,
                                            lr_final=training_args.position_lr_final*self.spatial_lr_scale,
                                            lr_delay_mult=training_args.position_lr_delay_mult,
                                            max_steps=training_args.position_lr_max_steps)

self.exposure_scheduler_args = get_expon_lr_func(training_args.exposure_lr_init, training_args.exposure_lr_final,
                                                lr_delay_steps=training_args.exposure_lr_delay_steps,
                                                lr_delay_mult=training_args.exposure_lr_delay_mult,
                                                max_steps=training_args.iterations)
```

#### Parameters


```python
def get_expon_lr_func(lr_init, lr_final, lr_delay_steps=0, lr_delay_mult=1.0, max_steps=1000000):
```
`lr_init:` This is the baseline peak learning rate from which the exponential decay begins.  
`lr_final:` This is the final learning rate reached at the end of training.  
`lr_delay_steps:` This is the number of steps required to complete the warm-up phase.  
`lr_delay_mult:` This is the starting multiplier applied to the learning rate at the very beginning of training.  
`max_steps:` This is the total number of training steps over which the learning rate decays to its final value.

#### How it works
Let's use `self.xyz_scheduler_args` as an example of how this function works

```python
self.xyz_scheduler_args = get_expon_lr_func(lr_init=training_args.position_lr_init*self.spatial_lr_scale,
                                            lr_final=training_args.position_lr_final*self.spatial_lr_scale,
                                            lr_delay_mult=training_args.position_lr_delay_mult,
                                            max_steps=training_args.position_lr_max_steps)
```
`lr_init:` opt.position_lr_init = 0.00016 * gaussians.spatial_lr_scale = 5.079339504241943(this value is from `create_from_pcd`) = $8.12 * 10^{-4}$  
`lr_final:` opt.position_lr_final = 0.0000016 * gaussians.spatial_lr_scale = 5.079339504241943 = $8.12 * 10^{-6}$  
`lr_delay_steps:` default value of this parameter is $0$ so in this process the value is $0$  
`lr_delay_mult:` opt.position_lr_delay_mult = $0.01$  
`max_steps:` opt.position_lr_max_steps = $30000$

```python
# inside get_expon_lr_func
def helper(step):
        if step < 0 or (lr_init == 0.0 and lr_final == 0.0):
            # Disable this parameter
            return 0.0
```
`helper` function's parameter __step__ is iteration of training
```python
        if lr_delay_steps > 0:
            # A kind of reverse cosine decay.
            delay_rate = lr_delay_mult + (1 - lr_delay_mult) * np.sin(
                0.5 * np.pi * np.clip(step / lr_delay_steps, 0, 1)
            )
        else:
            delay_rate = 1.0
```
since **lr_delay_steps == 0**, delay_rate is set to 1.0
```python
        t = np.clip(step / max_steps, 0, 1)
```
Set the value of t between 0 and 1.
```python
        log_lerp = np.exp(np.log(lr_init) * (1 - t) + np.log(lr_final) * t)
```
This calculates the exponentially decayed learning rate for the current step.
```python
        return delay_rate * log_lerp
```
since *delay_rate == 1.0*, $\ $ __helper__ function returns log_lerp which exponentially decay learning rate based on the current training process

```python
return helper
```
Finally the function `get_expon_lr_func` returns helper function

This is used like this
```python
def update_learning_rate(self, iteration):
        ''' Learning rate scheduling per step '''
        if self.pretrained_exposures is None:
            for param_group in self.exposure_optimizer.param_groups:
                param_group['lr'] = self.exposure_scheduler_args(iteration) # Here

        for param_group in self.optimizer.param_groups:
            if param_group["name"] == "xyz":
                lr = self.xyz_scheduler_args(iteration) # Here
                param_group['lr'] = lr
                return lr
```

### __lr Details from list l:__  

I calculated some *lrs*, but some are not accurate.  
For more details, look at [tutorial_3DGS](tutorial_3DGS.ipynb) chapter `Training Setup/Training Setup Specifics`

`self._xyz:` lr: *opt.position_lr_init* = 0.00016 * *gaussians.spatial_lr_scale* = 5.079339504241943(this value is from `create_from_pcd`) = $8.12 * 10^{-4}$  
`self._features_dc:` lr: *opt.feature_lr* = 0.0025  
`self._features_rest` lr: *opt.feature_lr/20* = 0.000125  
`self._opacity` lr: *opt.opactiy_lr* = 0.025  
`self._scaling` lr: *opt.scaling_lr* = 0.005  
`self._rotation` lr: *opt.rotation_lr* = 0.001

# Making Gaussians

```python
# gaussian_model.py 
def __init__(self, sh_degree, optimizer_type="default"):
        self.active_sh_degree = 0
        self.optimizer_type = optimizer_type
        self.max_sh_degree = sh_degree  
        self._xyz = torch.empty(0)
        self._features_dc = torch.empty(0)
        self._features_rest = torch.empty(0)
        self._scaling = torch.empty(0)
        self._rotation = torch.empty(0)
        self._opacity = torch.empty(0)
        self.max_radii2D = torch.empty(0)
        self.xyz_gradient_accum = torch.empty(0)
        self.denom = torch.empty(0)
        self.optimizer = None
        self.percent_dense = 0
        self.spatial_lr_scale = 0
        self.setup_functions() # Here

def setup_functions(self):
    def build_covariance_from_scaling_rotation(scaling, scaling_modifier, rotation):
        L = build_scaling_rotation(scaling_modifier * scaling, rotation) # Here
        actual_covariance = L @ L.transpose(1, 2) 
        symm = strip_symmetric(actual_covariance)
        return symm
        
    self.scaling_activation = torch.exp
    self.scaling_inverse_activation = torch.log

    self.covariance_activation = build_covariance_from_scaling_rotation

    self.opacity_activation = torch.sigmoid
    self.inverse_opacity_activation = inverse_sigmoid

    self.rotation_activation = torch.nn.functional.normalize

```
`setup_functions`에서 `actual_covariance`에 `build_scaling_rotation` 함수를 통해

 

```python

def build_scaling_rotation(s, r):
    L = torch.zeros((s.shape[0], 3, 3), dtype=torch.float, device="cuda")
    R = build_rotation(r) # Quaternion -> Rotation Matrix

    L[:,0,0] = s[:,0] 
    L[:,1,1] = s[:,1] 
    L[:,2,2] = s[:,2] # L Matrix를 대각행렬로 만듦

    L = R @ L
    return L
```
$$L = RS$$
를 만들고
```python
actual_covariance = L @ L.transpose(1, 2)
``` 
를 통해  
$$LL^T = \Sigma = RSS^TR^T$$
를 만들어낸다.

# Copying and Pruning 3D Gaussians

```python
# train.py Line 163
# Densification
    if iteration < opt.densify_until_iter:
        # Keep track of max radii in image-space for pruning
        gaussians.max_radii2D[visibility_filter] = torch.max(gaussians.max_radii2D[visibility_filter], radii[visibility_filter])
        gaussians.add_densification_stats(viewspace_point_tensor, visibility_filter)

        if iteration > opt.densify_from_iter and iteration % opt.densification_interval == 0:
            size_threshold = 20 if iteration > opt.opacity_reset_interval else None
            gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold, radii) # Here
                
        if iteration % opt.opacity_reset_interval == 0 or (dataset.white_background and iteration == opt.densify_from_iter):
            gaussians.reset_opacity()

```
`opt.densify_until_iter` = 15000이다. 즉, iteration이 15000보다 작으면 #Densification에 해당하는 코드가 실행된다.  
gaussians.max_radii2D[visibility_filter]: visibility_filter는 `render` 함수의 return 값 중 하나로 GaussianRasterizer의 return 값이다.


`densify_and_prune` 함수에서 학습을 통해 새로운 Gaussian을 만든다.
```python
# gaussian_model.py 
def densify_and_prune(self, max_grad, min_opacity, extent, max_screen_size, radii):
        grads = self.xyz_gradient_accum / self.denom
        grads[grads.isnan()] = 0.0

        self.tmp_radii = radii
        self.densify_and_clone(grads, max_grad, extent) # Here
        self.densify_and_split(grads, max_grad, extent)

        prune_mask = (self.get_opacity < min_opacity).squeeze()
        if max_screen_size:
            big_points_vs = self.max_radii2D > max_screen_size
            big_points_ws = self.get_scaling.max(dim=1).values > 0.1 * extent
            prune_mask = torch.logical_or(torch.logical_or(prune_mask, big_points_vs), big_points_ws)
        self.prune_points(prune_mask)
        tmp_radii = self.tmp_radii
        self.tmp_radii = None

        torch.cuda.empty_cache()

```
```python
def densify_and_clone(self, grads, grad_threshold, scene_extent):
    # Extract points that satisfy the gradient condition
    selected_pts_mask = torch.where(torch.norm(grads, dim=-1) >= grad_threshold, True, False)
    selected_pts_mask = torch.logical_and(selected_pts_mask,
                                                torch.max(self.get_scaling, dim=1).values <= self.percent_dense*scene_extent)
        
    new_xyz = self._xyz[selected_pts_mask]
    new_features_dc = self._features_dc[selected_pts_mask]
    new_features_rest = self._features_rest[selected_pts_mask]
    new_opacities = self._opacity[selected_pts_mask]
    new_scaling = self._scaling[selected_pts_mask]
    new_rotation = self._rotation[selected_pts_mask]

    new_tmp_radii = self.tmp_radii[selected_pts_mask]

    self.densification_postfix(new_xyz, new_features_dc, new_features_rest, new_opacities, new_scaling, new_rotation, new_tmp_radii

def densify_and_split(self, grads, grad_threshold, scene_extent, N=2):
    n_init_points = self.get_xyz.shape[0]
    # Extract points that satisfy the gradient condition
    padded_grad = torch.zeros((n_init_points), device="cuda")
    padded_grad[:grads.shape[0]] = grads.squeeze()
    selected_pts_mask = torch.where(padded_grad >= grad_threshold, True, False)
    selected_pts_mask = torch.logical_and(selected_pts_mask,
                                              torch.max(self.get_scaling, dim=1).values > self.percent_dense*scene_extent)

    stds = self.get_scaling[selected_pts_mask].repeat(N,1)
    means =torch.zeros((stds.size(0), 3),device="cuda")
    samples = torch.normal(mean=means, std=stds)
    rots = build_rotation(self._rotation[selected_pts_mask]).repeat(N,1,1)
    new_xyz = torch.bmm(rots, samples.unsqueeze(-1)).squeeze(-1) + self.get_xyz[selected_pts_mask].repeat(N, 1)
    new_scaling = self.scaling_inverse_activation(self.get_scaling[selected_pts_mask].repeat(N,1) / (0.8*N))
    new_rotation = self._rotation[selected_pts_mask].repeat(N,1)
    new_features_dc = self._features_dc[selected_pts_mask].repeat(N,1,1)
    new_features_rest = self._features_rest[selected_pts_mask].repeat(N,1,1)
    new_opacity = self._opacity[selected_pts_mask].repeat(N,1)
    new_tmp_radii = self.tmp_radii[selected_pts_mask].repeat(N)

    self.densification_postfix(new_xyz, new_features_dc, new_features_rest, new_opacity, new_scaling, new_rotation, new_tmp_radii)

    prune_filter = torch.cat((selected_pts_mask, torch.zeros(N * selected_pts_mask.sum(), device="cuda", dtype=bool)))
    self.prune_points(prune_filter)
```

```python

```

# Render
This explains how function `render` works

```python
render(viewpoint_cam, gaussians, pipe_args, bg, use_trained_exp=model_args.train_test_exp, separate_sh=SPARSE_ADAM_AVAILABLE)
```
This shows what parameter `render` function uses


```python
def render(viewpoint_camera, pc : GaussianModel, pipe, bg_color : torch.Tensor, scaling_modifier = 1.0, separate_sh = False, override_color = None, use_trained_exp=False):
    """
    Render the scene. 
    
    Background tensor (bg_color) must be on GPU!
    """
 
    # Create zero tensor. We will use it to make pytorch return gradients of the 2D (screen-space) means
    screenspace_points = torch.zeros_like(pc.get_xyz, dtype=pc.get_xyz.dtype, requires_grad=True, device="cuda") + 0
```
`screenspace_points:` $(number\ of\ points)*3$ matrix, all value with 0

```python
    try:
        screenspace_points.retain_grad()
    except:
        pass

    # Set up rasterization configuration
    tanfovx = math.tan(viewpoint_camera.FoVx * 0.5)
    tanfovy = math.tan(viewpoint_camera.FoVy * 0.5)
```
`tanfovx, tanfovy`: setting Field of View by tangent  
__Details:__  
For **viewpoint_cam.uid == 13**  
**FoVx** = 0.602981540771676  
**FoVy** = 1.0060968822522376  
**tanfovx** = 0.3109704250061455  
**tanfovy** = 0.5502673425137008

```python
    raster_settings = GaussianRasterizationSettings(
        image_height=int(viewpoint_camera.image_height),
        image_width=int(viewpoint_camera.image_width),
        tanfovx=tanfovx,
        tanfovy=tanfovy,
        bg=bg_color,
        scale_modifier=scaling_modifier,
        viewmatrix=viewpoint_camera.world_view_transform,
        projmatrix=viewpoint_camera.full_proj_transform,
        sh_degree=pc.active_sh_degree,
        campos=viewpoint_camera.camera_center,
        prefiltered=False,
        debug=pipe.debug,
        antialiasing=pipe.antialiasing
    )
```
`raster_settings:` Object of GaussianRasterizationSettings class

```python
    rasterizer = GaussianRasterizer(raster_settings=raster_settings)
    means3D = pc.get_xyz
    means2D = screenspace_points
    opacity = pc.get_opacity
```
`rasterizer:` Object of GaussianRasterizer class  
`means3D:` gaussians._xyz  
`means2D:` $(number\ of\ point) * 3$ matrix all value with 0   
`opacity:` $(number\ of\ point) * 1$ matrix with same opacity value

```python
    # If precomputed 3d covariance is provided, use it. If not, then it will be computed from
    # scaling / rotation by the rasterizer.
    scales = None
    rotations = None
    cov3D_precomp = None

    if pipe.compute_cov3D_python:
        cov3D_precomp = pc.get_covariance(scaling_modifier)
    else:
        scales = pc.get_scaling
        rotations = pc.get_rotation
```

```python

    # If precomputed colors are provided, use them. Otherwise, if it is desired to precompute colors
    # from SHs in Python, do it. If not, then SH -> RGB conversion will be done by rasterizer.
    shs = None
    colors_precomp = None
    if override_color is None:
        if pipe.convert_SHs_python:
            shs_view = pc.get_features.transpose(1, 2).view(-1, 3, (pc.max_sh_degree+1)**2)
            dir_pp = (pc.get_xyz - viewpoint_camera.camera_center.repeat(pc.get_features.shape[0], 1))
            dir_pp_normalized = dir_pp/dir_pp.norm(dim=1, keepdim=True)
            sh2rgb = eval_sh(pc.active_sh_degree, shs_view, dir_pp_normalized)
            colors_precomp = torch.clamp_min(sh2rgb + 0.5, 0.0)
        else:
            if separate_sh:
                dc, shs = pc.get_features_dc, pc.get_features_rest
            else:
                shs = pc.get_features
    else:
        colors_precomp = override_color

    # Rasterize visible Gaussians to image, obtain their radii (on screen). 
    if separate_sh:
        rendered_image, radii, depth_image = rasterizer(
            means3D = means3D,
            means2D = means2D,
            dc = dc,
            shs = shs,
            colors_precomp = colors_precomp,
            opacities = opacity,
            scales = scales,
            rotations = rotations,
            cov3D_precomp = cov3D_precomp)
    else:
        rendered_image, radii, depth_image = rasterizer(
            means3D = means3D,
            means2D = means2D,
            shs = shs,
            colors_precomp = colors_precomp,
            opacities = opacity,
            scales = scales,
            rotations = rotations,
            cov3D_precomp = cov3D_precomp)
        
    # Apply exposure to rendered image (training only)
    if use_trained_exp:
        exposure = pc.get_exposure_from_name(viewpoint_camera.image_name)
        rendered_image = torch.matmul(rendered_image.permute(1, 2, 0), exposure[:3, :3]).permute(2, 0, 1) + exposure[:3, 3,   None, None]

    # Those Gaussians that were frustum culled or had a radius of 0 were not visible.
    # They will be excluded from value updates used in the splitting criteria.
    rendered_image = rendered_image.clamp(0, 1)
    out = {
        "render": rendered_image,
        "viewspace_points": screenspace_points,
        "visibility_filter" : (radii > 0).nonzero(),
        "radii": radii,
        "depth" : depth_image
        }
    
    return out
```

# Outputs

By running train.py its ouputs are stored in directory [output/Test2_Result](output/Test2_Result)

### Details

Information [input.ply](output/Test2_Result/input.ply) have is the result of running convert.py. Which is 1768 point clouds.

## Results for 7000 iterations

In [4]:
ply_path = 'output/Test2_Result/point_cloud/iteration_7000/point_cloud.ply'
pcd = o3d.io.read_point_cloud(ply_path)

print(pcd)
points = np.asarray(pcd.points)
print(points)

o3d.visualization.draw_geometries([pcd])

PointCloud with 347527 points.
[[ 6.59872437 10.12901211  2.86574125]
 [ 0.22425154  1.65513897 12.2174387 ]
 [ 4.22987652 -1.58260691  9.34566116]
 ...
 [ 0.07556491  6.75840139  6.57672215]
 [ 4.2516675   7.14003801 10.84717178]
 [-0.48998436  5.14745998  7.08731127]]


## Results for 30000 iterations

In [3]:
ply_path = 'output/Test2_Result/point_cloud/iteration_30000/point_cloud.ply'
pcd = o3d.io.read_point_cloud(ply_path)

print(pcd)
points = np.asarray(pcd.points)
print(points)

o3d.visualization.draw_geometries([pcd])

PointCloud with 375184 points.
[[ 6.60873985 10.11532307  2.88246822]
 [ 0.17242943  1.56833577 12.10415363]
 [ 4.23568726 -1.58306515  9.3474226 ]
 ...
 [-1.06505299  5.10284138 12.32131481]
 [ 1.89028597  3.38411283 10.96808529]
 [-0.26036382  4.30767822 11.26516533]]


# Todo

Tutorial 만들기  
Gaussian을 직접 조작해서 Gaussian Splatting을 통해 어떤 식으로 scene에 나오게 되는지를 나타내게끔 함  
간단한 정육면체? 점을 찍는 ply 파일을 만들고 이를 training시켜서 사용  